const mongoose = require("mongoose");

// ======================================================
// Timeline Schema
// ------------------------------------------------------
// Represents a single week-by-week activity in the crop
// calendar. `originalDate` is the date generated by the
// AI Crop Planner at creation time and never changes.
// `currentDate` is the live, possibly-shifted date that
// the Weather Optimizer updates when rain/heat pushes an
// activity back. `weatherAffected` + `delayReason` let the
// PDF Generator and Notification Service explain *why* a
// date moved, and `completionDate` records when the farmer
// actually finished the activity (may differ from both
// scheduled dates).
// ======================================================

const timelineSchema = new mongoose.Schema(
  {
    // Human-readable week label, e.g. "Week 1".
    week: {
      type: String,
      required: [true, "Timeline week is required"],
      trim: true,
    },

    title: {
      type: String,
      required: [true, "Timeline title is required"],
      trim: true,
    },

    description: {
      type: String,
      required: [true, "Timeline description is required"],
      trim: true,
    },

    // Date originally computed by the AI Crop Planner. Immutable once set.
    originalDate: {
      type: Date,
      default: null,
    },

    // Live date used for display/notifications. Shifted by the Weather
    // Optimizer when weather delays an activity.
    currentDate: {
      type: Date,
      default: null,
    },

    status: {
      type: String,
      enum: {
        values: [
          "Upcoming",
          "Pending",
          "Completed",
          "Delayed",
          "Skipped",
          "Weather Delay",
        ],
        message: "{VALUE} is not a valid timeline status",
      },
      default: "Upcoming",
    },

    // True whenever the Weather Optimizer has shifted this activity
    // because of unfavourable weather (rain, storm, heatwave, etc.).
    weatherAffected: {
      type: Boolean,
      default: false,
    },

    // Short human-readable explanation for a delay/skip, shown in the
    // PDF report and push notifications.
    delayReason: {
      type: String,
      trim: true,
      default: null,
    },

    // Timestamp of when the farmer actually completed the activity.
    completionDate: {
      type: Date,
      default: null,
    },
  },
  { _id: false }
);

// ======================================================
// Location Schema
// ------------------------------------------------------
// Normalized farm location. Latitude/longitude are stored
// so the Weather Engine can call weather APIs directly
// without re-geocoding on every request.
// ======================================================

const locationSchema = new mongoose.Schema(
  {
    state: {
      type: String,
      required: [true, "State is required"],
      trim: true,
    },

    district: {
      type: String,
      required: [true, "District is required"],
      trim: true,
    },

    // Optional — not every farmer profile includes village-level detail.
    village: {
      type: String,
      trim: true,
      default: null,
    },

    latitude: {
      type: Number,
      min: -90,
      max: 90,
      default: null,
    },

    longitude: {
      type: Number,
      min: -180,
      max: 180,
      default: null,
    },
  },
  { _id: false }
);

// ======================================================
// Weather Snapshot Schema
// ------------------------------------------------------
// Always holds the LATEST weather reading for this
// itinerary's location, refreshed by the Weather Engine.
// This is a snapshot, not a history — historical readings
// are out of scope for this model.
// ======================================================

const weatherSchema = new mongoose.Schema(
  {
    temperature: {
      type: Number,
      default: null,
    },

    humidity: {
      type: Number,
      min: 0,
      max: 100,
      default: null,
    },

    rainfall: {
      type: Number,
      min: 0,
      default: null,
    },

    windSpeed: {
      type: Number,
      min: 0,
      default: null,
    },

    condition: {
      type: String,
      trim: true,
      default: null,
    },

    // Short AI-generated recommendation tied to current conditions
    // (e.g. "Delay spraying — rain expected within 6 hours").
    recommendation: {
      type: String,
      trim: true,
      default: null,
    },

    lastUpdated: {
      type: Date,
      default: null,
    },
  },
  { _id: false }
);

// ======================================================
// Today's Task Schema
// ------------------------------------------------------
// Single most important field surfaced on the Farmer
// Dashboard and PDF cover section. Recomputed automatically
// by the Weather Optimizer whenever weather conditions
// change the recommended action for the current day.
// ======================================================

const todayTaskSchema = new mongoose.Schema(
  {
    activity: {
      type: String,
      trim: true,
      default: null,
    },

    scheduledDate: {
      type: Date,
      default: null,
    },

    status: {
      type: String,
      enum: {
        values: [
          "Upcoming",
          "Pending",
          "Completed",
          "Delayed",
          "Skipped",
          "Weather Delay",
        ],
        message: "{VALUE} is not a valid today-task status",
      },
      default: "Upcoming",
    },

    recommendation: {
      type: String,
      trim: true,
      default: null,
    },

    lastUpdated: {
      type: Date,
      default: null,
    },
  },
  { _id: false }
);

// ======================================================
// AI Summary Schema
// ------------------------------------------------------
// High-level, at-a-glance figures generated once by the
// AI Crop Planner (Gemini). Consumed directly by the PDF
// Generator's "AI Summary" statistic cards and the Farmer
// Dashboard overview.
// ======================================================

const aiSummarySchema = new mongoose.Schema(
  {
    cropDuration: {
      type: String,
      trim: true,
      default: null,
    },

    bestSowingSeason: {
      type: String,
      trim: true,
      default: null,
    },

    harvestSeason: {
      type: String,
      trim: true,
      default: null,
    },

    expectedYield: {
      type: String,
      trim: true,
      default: null,
    },

    estimatedCost: {
      type: String,
      trim: true,
      default: null,
    },

    estimatedIncome: {
      type: String,
      trim: true,
      default: null,
    },

    estimatedProfit: {
      type: String,
      trim: true,
      default: null,
    },
  },
  { _id: false }
);

// ======================================================
// Equipment Schema
// ------------------------------------------------------
// Improved to support linking to a real Equipment catalog
// document (for booking/rental flows) while remaining
// backward compatible with plain AI-generated suggestions
// that have no catalog match yet.
// ======================================================

const equipmentSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, "Equipment name is required"],
      trim: true,
    },

    purpose: {
      type: String,
      trim: true,
      default: null,
    },

    estimatedRent: {
      type: String,
      trim: true,
      default: null,
    },

    availability: {
      type: String,
      enum: {
        values: ["Available", "Unavailable", "Check Availability"],
        message: "{VALUE} is not a valid availability status",
      },
      default: "Check Availability",
    },

    // Optional link to an actual Equipment catalog/inventory document,
    // populated once the farmer books through FarmFleet's marketplace.
    equipmentRef: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Equipment",
      default: null,
    },
  },
  { _id: false }
);

// ======================================================
// Labour Schema
// ------------------------------------------------------
// Improved to separate "workers required" from "workers
// actually available" so the Labour Recommendation module
// can surface shortages to the farmer ahead of time.
// ======================================================

const labourSchema = new mongoose.Schema(
  {
    activity: {
      type: String,
      required: [true, "Labour activity is required"],
      trim: true,
    },

    workersRequired: {
      type: Number,
      min: 0,
      default: 0,
    },

    estimatedDays: {
      type: Number,
      min: 0,
      default: 0,
    },

    availableWorkers: {
      type: Number,
      min: 0,
      default: 0,
    },

    estimatedCost: {
      type: String,
      trim: true,
      default: null,
    },
  },
  { _id: false }
);

// ======================================================
// Fertilizer Schema (unchanged)
// ======================================================

const fertilizerSchema = new mongoose.Schema(
  {
    stage: {
      type: String,
      trim: true,
    },
    fertilizer: {
      type: String,
      trim: true,
    },
    quantity: {
      type: String,
      trim: true,
    },
    time: {
      type: String,
      trim: true,
    },
  },
  { _id: false }
);

// ======================================================
// Irrigation Schema (unchanged)
// ======================================================

const irrigationSchema = new mongoose.Schema(
  {
    stage: {
      type: String,
      trim: true,
    },
    frequency: {
      type: String,
      trim: true,
    },
    waterRequirement: {
      type: String,
      trim: true,
    },
  },
  { _id: false }
);

// ======================================================
// Pest & Disease Schema (unchanged)
// ======================================================

const pestSchema = new mongoose.Schema(
  {
    problem: {
      type: String,
      trim: true,
    },
    solution: {
      type: String,
      trim: true,
    },
  },
  { _id: false }
);

// ======================================================
// Seed Recommendation Schema (unchanged)
// ======================================================

const seedRecommendationSchema = new mongoose.Schema(
  {
    variety: {
      type: String,
      trim: true,
    },
    seedQuantity: {
      type: String,
      trim: true,
    },
    estimatedCost: {
      type: String,
      trim: true,
    },
  },
  { _id: false }
);

// ======================================================
// PDF Info Schema
// ------------------------------------------------------
// Tracks whether a report has been generated for this
// itinerary and where it lives, so the PDF Generator can
// skip regeneration when nothing has changed, and the
// Notification Service can attach/link the correct file.
// ======================================================

const pdfSchema = new mongoose.Schema(
  {
    generated: {
      type: Boolean,
      default: false,
    },

    generatedAt: {
      type: Date,
      default: null,
    },

    // Incremented every time the report is regenerated, so old links
    // shared with the farmer can be invalidated/refreshed.
    version: {
      type: Number,
      default: 0,
      min: 0,
    },

    filePath: {
      type: String,
      trim: true,
      default: null,
    },
  },
  { _id: false }
);

// ======================================================
// Notification History Schema
// ------------------------------------------------------
// Lightweight log of notifications already sent for this
// itinerary, used purely to prevent duplicate emails/SMS
// pushes (e.g. don't re-send a "weather delay" alert twice
// for the same event).
// ======================================================

const notificationSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      enum: {
        values: [
          "Today Task Reminder",
          "Weather Delay",
          "Weather Alert",
          "Timeline Update",
          "Report Generated",
          "General",
        ],
        message: "{VALUE} is not a valid notification type",
      },
      required: [true, "Notification type is required"],
    },

    sentAt: {
      type: Date,
      default: Date.now,
    },

    status: {
      type: String,
      enum: {
        values: ["Sent", "Failed", "Pending"],
        message: "{VALUE} is not a valid notification status",
      },
      default: "Pending",
    },
  },
  { _id: false }
);

// ======================================================
// Crop Itinerary Schema
// ------------------------------------------------------
// Single source of truth for a farmer's AI-generated crop
// plan. Every module (AI Crop Planner, Weather Engine,
// Weather Optimizer, PDF Generator, Notification Service,
// Equipment/Labour Recommendation, Farmer Dashboard, and
// the future AI Chat Assistant) reads and writes this
// document, so field names and shapes here are considered
// a stable contract across the backend.
// ======================================================

const cropItinerarySchema = new mongoose.Schema(
  {
    // Owning farmer. Indexed for fast "all itineraries for this farmer"
    // dashboard queries.
    farmer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Farmer",
      required: [true, "Farmer reference is required"],
    },

    crop: {
      type: String,
      required: [true, "Crop name is required"],
      trim: true,
    },

    // Normalized location — see locationSchema above.
    location: {
      type: locationSchema,
      default: () => ({}),
    },

    soilType: {
      type: String,
      trim: true,
      default: null,
    },

    landArea: {
      type: String,
      trim: true,
      default: null,
    },

    waterSource: {
      type: String,
      trim: true,
      default: null,
    },

    budget: {
      type: String,
      trim: true,
      default: null,
    },

    // Consolidated AI-generated headline figures.
    aiSummary: {
      type: aiSummarySchema,
      default: () => ({}),
    },

    // Live weather snapshot for the farm's location.
    weather: {
      type: weatherSchema,
      default: () => ({}),
    },

    // The single activity the farmer should focus on right now.
    todayTask: {
      type: todayTaskSchema,
      default: () => ({}),
    },

    // Week-by-week crop calendar.
    timeline: {
      type: [timelineSchema],
      default: [],
    },

    landPreparation: {
      type: [String],
      default: [],
    },

    seedRecommendation: {
      type: seedRecommendationSchema,
      default: () => ({}),
    },

    fertilizerSchedule: {
      type: [fertilizerSchema],
      default: [],
    },

    irrigationSchedule: {
      type: [irrigationSchema],
      default: [],
    },

    weedManagement: {
      type: [String],
      default: [],
    },

    pestAndDiseaseManagement: {
      type: [pestSchema],
      default: [],
    },

    equipmentRequired: {
      type: [equipmentSchema],
      default: [],
    },

    labourRequirement: {
      type: [labourSchema],
      default: [],
    },

    precautions: {
      type: [String],
      default: [],
    },

    tips: {
      type: [String],
      default: [],
    },

    // governmentSchemes removed — FarmFleet AI no longer supports this
    // feature. Do not re-add without a migration plan for existing docs.

    // Report generation bookkeeping.
    pdf: {
      type: pdfSchema,
      default: () => ({}),
    },

    // De-duplication log for the Notification Service.
    notifications: {
      type: [notificationSchema],
      default: [],
    },

    // Raw, unmodified Gemini response — kept for audits/debugging and to
    // allow re-deriving fields without re-calling the AI model.
    aiResponse: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // ------------------------------------------------------------------
    // Weather monitoring control
    // ------------------------------------------------------------------
    weatherMonitoringEnabled: {
      type: Boolean,
      default: true,
    },

    lastWeatherCheck: {
      type: Date,
      default: null,
    },

    // When the Weather Engine should next poll for this itinerary,
    // letting a scheduler query cheaply for "due" documents instead of
    // checking every itinerary on every run.
    nextWeatherCheck: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

// ======================================================
// Indexes
// ------------------------------------------------------
// - farmer: fast lookup of a farmer's itineraries (dashboard).
// - crop: supports crop-based analytics/filtering.
// - createdAt: supports "most recent first" listing.
// - weatherMonitoringEnabled + nextWeatherCheck: lets the Weather
//   Engine's scheduled job efficiently find itineraries that are due
//   for a weather refresh without a full collection scan.
// ======================================================

cropItinerarySchema.index({ farmer: 1 });
cropItinerarySchema.index({ crop: 1 });
cropItinerarySchema.index({ createdAt: -1 });
cropItinerarySchema.index({ weatherMonitoringEnabled: 1, nextWeatherCheck: 1 });

// ======================================================
// Export Model
// ======================================================

module.exports = mongoose.model("CropItinerary", cropItinerarySchema);