/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OwnerSetupRouteImport } from './routes/owner-setup'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRenterRouteImport } from './routes/login-renter'
import { Route as LoginOwnerRouteImport } from './routes/login-owner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RenterSearchRouteImport } from './routes/renter.search'
import { Route as RenterProfileRouteImport } from './routes/renter.profile'
import { Route as RenterDashboardRouteImport } from './routes/renter.dashboard'
import { Route as RenterBookingsRouteImport } from './routes/renter.bookings'
import { Route as OwnerReviewRouteImport } from './routes/owner.review'
import { Route as OwnerProfileRouteImport } from './routes/owner.profile'
import { Route as OwnerEquipmentRouteImport } from './routes/owner.equipment'
import { Route as OwnerEarningsRouteImport } from './routes/owner.earnings'
import { Route as OwnerDashboardRouteImport } from './routes/owner.dashboard'
import { Route as OwnerBookingsRouteImport } from './routes/owner.bookings'
import { Route as RenterEquipmentIdRouteImport } from './routes/renter.equipment.$id'
import { Route as RenterBookingIdRouteImport } from './routes/renter.booking.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSetupRoute = OwnerSetupRouteImport.update({
  id: '/owner-setup',
  path: '/owner-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRenterRoute = LoginRenterRouteImport.update({
  id: '/login-renter',
  path: '/login-renter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOwnerRoute = LoginOwnerRouteImport.update({
  id: '/login-owner',
  path: '/login-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RenterSearchRoute = RenterSearchRouteImport.update({
  id: '/renter/search',
  path: '/renter/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RenterProfileRoute = RenterProfileRouteImport.update({
  id: '/renter/profile',
  path: '/renter/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RenterDashboardRoute = RenterDashboardRouteImport.update({
  id: '/renter/dashboard',
  path: '/renter/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RenterBookingsRoute = RenterBookingsRouteImport.update({
  id: '/renter/bookings',
  path: '/renter/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerReviewRoute = OwnerReviewRouteImport.update({
  id: '/owner/review',
  path: '/owner/review',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerProfileRoute = OwnerProfileRouteImport.update({
  id: '/owner/profile',
  path: '/owner/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerEquipmentRoute = OwnerEquipmentRouteImport.update({
  id: '/owner/equipment',
  path: '/owner/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerEarningsRoute = OwnerEarningsRouteImport.update({
  id: '/owner/earnings',
  path: '/owner/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/owner/bookings',
  path: '/owner/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const RenterEquipmentIdRoute = RenterEquipmentIdRouteImport.update({
  id: '/renter/equipment/$id',
  path: '/renter/equipment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RenterBookingIdRoute = RenterBookingIdRouteImport.update({
  id: '/renter/booking/$id',
  path: '/renter/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login-owner': typeof LoginOwnerRoute
  '/login-renter': typeof LoginRenterRoute
  '/not-found': typeof NotFoundRoute
  '/owner-setup': typeof OwnerSetupRoute
  '/register': typeof RegisterRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/earnings': typeof OwnerEarningsRoute
  '/owner/equipment': typeof OwnerEquipmentRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/review': typeof OwnerReviewRoute
  '/renter/bookings': typeof RenterBookingsRoute
  '/renter/dashboard': typeof RenterDashboardRoute
  '/renter/profile': typeof RenterProfileRoute
  '/renter/search': typeof RenterSearchRoute
  '/renter/booking/$id': typeof RenterBookingIdRoute
  '/renter/equipment/$id': typeof RenterEquipmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login-owner': typeof LoginOwnerRoute
  '/login-renter': typeof LoginRenterRoute
  '/not-found': typeof NotFoundRoute
  '/owner-setup': typeof OwnerSetupRoute
  '/register': typeof RegisterRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/earnings': typeof OwnerEarningsRoute
  '/owner/equipment': typeof OwnerEquipmentRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/review': typeof OwnerReviewRoute
  '/renter/bookings': typeof RenterBookingsRoute
  '/renter/dashboard': typeof RenterDashboardRoute
  '/renter/profile': typeof RenterProfileRoute
  '/renter/search': typeof RenterSearchRoute
  '/renter/booking/$id': typeof RenterBookingIdRoute
  '/renter/equipment/$id': typeof RenterEquipmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login-owner': typeof LoginOwnerRoute
  '/login-renter': typeof LoginRenterRoute
  '/not-found': typeof NotFoundRoute
  '/owner-setup': typeof OwnerSetupRoute
  '/register': typeof RegisterRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/earnings': typeof OwnerEarningsRoute
  '/owner/equipment': typeof OwnerEquipmentRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/review': typeof OwnerReviewRoute
  '/renter/bookings': typeof RenterBookingsRoute
  '/renter/dashboard': typeof RenterDashboardRoute
  '/renter/profile': typeof RenterProfileRoute
  '/renter/search': typeof RenterSearchRoute
  '/renter/booking/$id': typeof RenterBookingIdRoute
  '/renter/equipment/$id': typeof RenterEquipmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login-owner'
    | '/login-renter'
    | '/not-found'
    | '/owner-setup'
    | '/register'
    | '/owner/bookings'
    | '/owner/dashboard'
    | '/owner/earnings'
    | '/owner/equipment'
    | '/owner/profile'
    | '/owner/review'
    | '/renter/bookings'
    | '/renter/dashboard'
    | '/renter/profile'
    | '/renter/search'
    | '/renter/booking/$id'
    | '/renter/equipment/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login-owner'
    | '/login-renter'
    | '/not-found'
    | '/owner-setup'
    | '/register'
    | '/owner/bookings'
    | '/owner/dashboard'
    | '/owner/earnings'
    | '/owner/equipment'
    | '/owner/profile'
    | '/owner/review'
    | '/renter/bookings'
    | '/renter/dashboard'
    | '/renter/profile'
    | '/renter/search'
    | '/renter/booking/$id'
    | '/renter/equipment/$id'
  id:
    | '__root__'
    | '/'
    | '/login-owner'
    | '/login-renter'
    | '/not-found'
    | '/owner-setup'
    | '/register'
    | '/owner/bookings'
    | '/owner/dashboard'
    | '/owner/earnings'
    | '/owner/equipment'
    | '/owner/profile'
    | '/owner/review'
    | '/renter/bookings'
    | '/renter/dashboard'
    | '/renter/profile'
    | '/renter/search'
    | '/renter/booking/$id'
    | '/renter/equipment/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginOwnerRoute: typeof LoginOwnerRoute
  LoginRenterRoute: typeof LoginRenterRoute
  NotFoundRoute: typeof NotFoundRoute
  OwnerSetupRoute: typeof OwnerSetupRoute
  RegisterRoute: typeof RegisterRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerEarningsRoute: typeof OwnerEarningsRoute
  OwnerEquipmentRoute: typeof OwnerEquipmentRoute
  OwnerProfileRoute: typeof OwnerProfileRoute
  OwnerReviewRoute: typeof OwnerReviewRoute
  RenterBookingsRoute: typeof RenterBookingsRoute
  RenterDashboardRoute: typeof RenterDashboardRoute
  RenterProfileRoute: typeof RenterProfileRoute
  RenterSearchRoute: typeof RenterSearchRoute
  RenterBookingIdRoute: typeof RenterBookingIdRoute
  RenterEquipmentIdRoute: typeof RenterEquipmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-setup': {
      id: '/owner-setup'
      path: '/owner-setup'
      fullPath: '/owner-setup'
      preLoaderRoute: typeof OwnerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-renter': {
      id: '/login-renter'
      path: '/login-renter'
      fullPath: '/login-renter'
      preLoaderRoute: typeof LoginRenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-owner': {
      id: '/login-owner'
      path: '/login-owner'
      fullPath: '/login-owner'
      preLoaderRoute: typeof LoginOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renter/search': {
      id: '/renter/search'
      path: '/renter/search'
      fullPath: '/renter/search'
      preLoaderRoute: typeof RenterSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renter/profile': {
      id: '/renter/profile'
      path: '/renter/profile'
      fullPath: '/renter/profile'
      preLoaderRoute: typeof RenterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renter/dashboard': {
      id: '/renter/dashboard'
      path: '/renter/dashboard'
      fullPath: '/renter/dashboard'
      preLoaderRoute: typeof RenterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renter/bookings': {
      id: '/renter/bookings'
      path: '/renter/bookings'
      fullPath: '/renter/bookings'
      preLoaderRoute: typeof RenterBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/review': {
      id: '/owner/review'
      path: '/owner/review'
      fullPath: '/owner/review'
      preLoaderRoute: typeof OwnerReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/profile': {
      id: '/owner/profile'
      path: '/owner/profile'
      fullPath: '/owner/profile'
      preLoaderRoute: typeof OwnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/equipment': {
      id: '/owner/equipment'
      path: '/owner/equipment'
      fullPath: '/owner/equipment'
      preLoaderRoute: typeof OwnerEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/earnings': {
      id: '/owner/earnings'
      path: '/owner/earnings'
      fullPath: '/owner/earnings'
      preLoaderRoute: typeof OwnerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/owner/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renter/equipment/$id': {
      id: '/renter/equipment/$id'
      path: '/renter/equipment/$id'
      fullPath: '/renter/equipment/$id'
      preLoaderRoute: typeof RenterEquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renter/booking/$id': {
      id: '/renter/booking/$id'
      path: '/renter/booking/$id'
      fullPath: '/renter/booking/$id'
      preLoaderRoute: typeof RenterBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginOwnerRoute: LoginOwnerRoute,
  LoginRenterRoute: LoginRenterRoute,
  NotFoundRoute: NotFoundRoute,
  OwnerSetupRoute: OwnerSetupRoute,
  RegisterRoute: RegisterRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerEarningsRoute: OwnerEarningsRoute,
  OwnerEquipmentRoute: OwnerEquipmentRoute,
  OwnerProfileRoute: OwnerProfileRoute,
  OwnerReviewRoute: OwnerReviewRoute,
  RenterBookingsRoute: RenterBookingsRoute,
  RenterDashboardRoute: RenterDashboardRoute,
  RenterProfileRoute: RenterProfileRoute,
  RenterSearchRoute: RenterSearchRoute,
  RenterBookingIdRoute: RenterBookingIdRoute,
  RenterEquipmentIdRoute: RenterEquipmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
